library(quanteda)

doc.corpus <- corpus(df)
doc.tokens <- tokens(doc.corpus)
doc.tokens <- tokens(doc.tokens, remove_punct = TRUE, remove_numbers = TRUE)
doc.tokens <- tokens_select(doc.tokens, stopwords('german'), selection = "remove")
doc.tokens <- tokens_wordstem(doc.tokens)
doc.tokens <- tokens_tolower(doc.tokens)
doc.dfm <- dfm(doc.tokens)
#summary(doc.dfm)
#topfeatures(doc.dfm, 5)